backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "catalog"
    label: "Каталог"
    files:
      - label: "Всі товари"
        name: "products"
        file: "products.json"
        format: "json"
        fields:
          - name: "items"
            label: "Список прикрас"
            widget: "list"
            fields:
              - { label: "Назва", name: "name", widget: "string" }
              - { label: "Ціна", name: "price", widget: "number", value_type: "int" }
              - { label: "Категорія", name: "category", widget: "string" }
              - { label: "Зображення", name: "image", widget: "image" }
              - { label: "Опис", name: "mood", widget: "text" }
              - { label: "ID", name: "id", widget: "hidden" }