collections:
  - name: "catalog"
    label: "Каталог"
    files:
      - label: "Всі товари"
        name: "products"
        file: "products.json"
        format: "json"
        fields:
          - name: "items"
            label: "Товари"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "hidden" } # Зробимо його прихованим, щоб не було помилок
              - { label: "Назва", name: "name", widget: "string" }
              - { label: "Ціна", name: "price", widget: "string" } # Змінюємо на string для стабільності
              - { label: "Категорія", name: "category", widget: "string" }
              - { label: "Зображення", name: "image", widget: "image" }
              - { label: "Опис (mood)", name: "mood", widget: "text" }